package thd.game.level;

/**
 * Public class that manages level 4.
 */

public class Level4 extends Level {

    /**
     * Creates a new level 4.
     */
    public Level4() {
        this.name = "        Level 4" +"\n"+"\n"+ "Dreaming or Not?";
        number = 4;
        worldOffsetColumns = 0;
        worldOffsetLines = 0;
        background = "game_background_4.png";
        if (difficulty.equals(Difficulty.STANDARD)){
            world = """
                                                                                      G                        *H                          NN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \s
                                                                                      G                        DD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \s
                                                                                      G                        *                                                                     C             RR                               O                                  SS                                                          S                                                                                     7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \s
                                                                           E          G                        *                                                                     W     III     DD                                                                  II                R                                        III                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \s
                                                                           CR      R  G                        *                                   C                 C    C                        DD         Y       Y            RRR                                                  RD               R        R                                                                                     NNNNN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \s
                                                                          HRD      D  D                              III                  IIII     W                 W    W                        DD            RRR           CCRRDDDRRCC                                             RDD               D        D                                                                       C             N   N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \s
                                                               Y         CRDD      D  DNNNN       D                                      II                                      C                 DD        CCRRDDDRRCC       RRDDDDDDDRR                                    CCC      DDD               D        D         E                                                            III            N   N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \s
                    I                                                    RDDD      D  D           D                                     II              C      C                 W                 DD        RRDDDDDDDRR       DDDDDDDDDDD                                    III      DDD              RD        DR                                                               S                    NCCCN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \s
                                                   G                        R      D  DE      Y  OD        CCCC                S       II               W      W                                   DD        DDDDDDDDDDD         DDDDDDD          Y                                    DDD              DD   WW   DD        N    RRRRR   Y          RRRRR     III                  W                    NNNNN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \s
                           10X                     G                        D     RD  D          HD       RRRRRR              III     II                                                           DD          DDDDDDD             DDD              RRR                II              DDD              DD        DD             DDDDD              DDDDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \s
                                                   G                        D      D  DDDDD  DDDDDD       DDDDDD                                                                                   DD            DDD                            CCRRDDDRRCC                            DDD             RDD        DDR            DDDDDRRRR      RRRRDDDDD             CC                                                E                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \s
                                                   G                        D      D                      DDDDDD                                                                                   DD                                           RRDDDDDDDRR                            DDD             DDDHY     HDDD            DDDDDDDDD CCCC DDDDDDDDD             WW     II                                          9  0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \s
                                    CCCC           G                        D      D                     EDDDDDD                                                                                   DD                                           DDDDDDDDDDD      G                        *            DDD        DDD       G                        DDDD                                         G                        G                        *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \s
                   G                        *     DG                        D     SD                      DDDDDD                                                                                   DD                                             DDDDDDD        G                        *        G                        G                        DDDD                                         G                        G                        *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \s
                                                  D                         D     RRG                        RRR                                                                                   DD                                               DDD                                                                                              DDDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \s
                                                                                                             DDD                                                                                   DD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \s
                   """;
        } else if (difficulty.equals(Difficulty.EASY)){
            world = """
                                                                                      G                        *H                          NN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \s
                                                                                      G                        DD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \s
                                                                                      G                        *                                                                     C             RR                                                                  SS                                                          S                                                                                     7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \s
                                                                                      G                        *                                                                     W     III     DD                                                                  II                R                                        III                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \s
                                                                           CR      R  G                        *                                   C                 C    C                        DD         Y       Y            RRR                                                  RD               R        R                                                                                     NNNNN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \s
                                                                          HRD      D  D                              III                  IIII     W                 W    W                        DD            RRR           CCRRDDDRRCC                                             RDD               D        D                                                                       C             N   N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \s
                                                               Y         CRDD      D  DNNNN       D                                      II                                      C                 DD        CCRRDDDRRCC       RRDDDDDDDRR                                    CCC      DDD               D        D         E                                                            III            N   N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \s
                    I                                                    RDDD      D  D           D                                     II              C      C                 I                 DD        RRDDDDDDDRR       DDDDDDDDDDD                                    III      DDD              RD        DR                                                               S                    NCCCN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \s
                                                   G                        R      D  D       Y   D        CCCC                S       II               I      I                                   DD        DDDDDDDDDDD         DDDDDDD          Y                                    DDD              DD   WW   DD        N    RRRRR   Y          RRRRR     III                  W                    NNNNN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \s
                           10X                     G                        D     RD  D          HD       RRRRRR              III     II                                                           DD          DDDDDDD             DDD              RRR                II              DDD              DD        DD             DDDDD              DDDDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \s
                                                   G                        D      D  DDDDD  DDDDDD       DDDDDD                                                                                   DD            DDD                            CCRRDDDRRCC                            DDD             RDD        DDR            DDDDDRRRR      RRRRDDDDD             CC                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \s
                                                   G                        D      D                      DDDDDD                                                                                   DD                                           RRDDDDDDDRR                            DDD             DDDHY     HDDD            DDDDDDDDD CCCC DDDDDDDDD             II     II                                          9  0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \s
                                    CCCC           G                        D      D                     EDDDDDD                                                                                   DD                                           DDDDDDDDDDD      G                        *            DDD        DDD       G                        DDDD                                         G                        G                        *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \s
                   G                        *     DG                        D     SD                      DDDDDD                                                                                   DD                                             DDDDDDD        G                        *        G                        G                        DDDD                                         G                        G                        *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \s
                                                  D                         D     RRG                        RRR                                                                                   DD                                               DDD                                                                                              DDDD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \s
                                                                                                             DDD                                                                                   DD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \s
                   """;
        }

    }

     /*
     Ratio 32x18 with scaling 50
     Self-destructive Objects: Blocks, Collectables after -(2 * GameView.WIDTH) and 5 seconds countdown;
        X = Hero, 3 Lines from Ground
        G = Ground, Ground is Long 24 chars, * indicates end of ground, 6 spaces apart for gap
        Y = EnemyYourei, 1 Lines from Ground where Ground = 0
        O = EnemyOnre, 1 Lines from Ground
        E = EnemyGotoku, 1 Lines from Ground
        C = Collectable coin,  Lines from Ground
        H = Collectable heart,  Lines from Ground
        S = Collectable shuriken,  Lines from Ground
        I = Block of Iron, 5 Blocks from other block for jump
        W = Block of Wood
        D = Block of Dirt
        R = Block of Grass
        N = Block of Coin
        0 = Left Border, y-coordinate is fixed!
        1 = Left Border House, the position is fixed!
        9 = Right Border Goal, y-coordinate is fixed!

        7 = Right Border House, 10 lines from ground
         */
}
